name: irondash_message_channel
description: Dart interface to irondash MessageChannel.
version: 0.7.0
homepage: https://github.com/irondash/irondash

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=2.2.1"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
